# Generated by Django 5.1.6 on 2025-03-11 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/images/')),
                ('display_fullwidth', models.BooleanField(default=False)),
                ('hidden_title', models.BooleanField(default=False)),
                ('hidden_image', models.BooleanField(default=False)),
                ('display_link', models.BooleanField(default=False)),
                ('card_show', models.BooleanField(default=True)),
                ('hidden', models.BooleanField(default=False)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('enable_special_category', models.BooleanField(default=False)),
                ('special_category_type', models.CharField(blank=True, max_length=255, null=True)),
                ('display_product_in_separate_category', models.BooleanField(default=False)),
                ('view_format', models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='category.category')),
                ('promotions', models.ManyToManyField(blank=True, to='promotion.promotion')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
