# Generated by Django 5.1.6 on 2025-02-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='menu/covers/')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='menu/logos/')),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='menu/categories/')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='menu/products/')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.license')),
            ],
        ),
    ]
