# Generated by Django 5.1.6 on 2025-02-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='app_icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/aap_icon/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='cart_footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='category_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/categories/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='chef_recommends_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/recommends/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='desktop_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/desktop/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='discount_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='display_categories_in_home_screen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='display_product_variation_prices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='display_properties_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='header_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='loading_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/loading/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_type',
            field=models.CharField(choices=[('GRID_WITH_IMAGES', 'Grid with images'), ('GRID_WITH_TEXT', 'Grid with Text')], default='GRID_WITH_IMAGES', max_length=20),
        ),
        migrations.AddField(
            model_name='menu',
            name='product_footer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='skip_onboarding_screen',
            field=models.BooleanField(default=False),
        ),
    ]
